language: java

dist: trusty
sudo: false

addons:
  chrome: stable

matrix:
  fast_finish: true
  allow_failures:
    - env: TEST_TYPE=examples CAPA="browserName:chrome,platform:Windows 7,screenResolution:1680x1050"

env:
  - TEST_TYPE=acceptance-test
  - TEST_TYPE=examples CAPA="browserName:chrome,platform:Windows 7,screenResolution:1680x1050"

cache:
  directories:
  - $HOME/.m2

script:
  - jdk_switcher use openjdk7
  - travis_wait 60 ./travis_build_and_test.sh

after_success:
  - "[[ \"${TRAVIS_PULL_REQUEST}\" == \"false\" && \"${TRAVIS_BRANCH}\" == \"master\" && \"${TEST_TYPE}\" == \"acceptance-test\" ]] && { ./travis_publish_results.sh target/*.zip hsac-fitnesse-fixtures-snapshot-standalone.zip; python travis_add_server.py; mvn -DskipTests deploy --settings ~/.m2/mySettings.xml; };"
